--Q1. What is the total revenue generated by male vs. female customers?

SELECT 
gender,
SUM(purchase_amount) as total_revenue,
COUNT (customer_id) as total_customers,
-- Revenue percentage (share of total)
CAST(ROUND(SUM(purchase_amount) * 100.0 / SUM(SUM(purchase_amount)) OVER(), 2) AS DECIMAL(10,2)) as revenue_percentage 
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

WITH category_avg AS (
    SELECT 
        category,
        AVG(purchase_amount) as avg_by_category
    FROM customer
    GROUP BY category
)
SELECT 
    c.customer_id,
    c.age, 
    c.age_group,
    c.category,
    c.purchase_amount,
    ca.avg_by_category,
    ROUND((c.purchase_amount - ca.avg_by_category), 2) as amount_above_average
FROM customer c
JOIN category_avg ca ON c.category = ca.category
WHERE c.discount_applied = 'Yes' 
    AND c.purchase_amount > ca.avg_by_category
ORDER BY c.category, c.purchase_amount DESC;


--Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5
item_purchased,
category,
ROUND(AVG(review_rating),2) as avg_product_rating
FROM customer
GROUP BY category, item_purchased 
ORDER BY avg_product_rating DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT TOP 5 * FROM customer

SELECT Distinct shipping_type FROM customer

SELECT 
category,
shipping_type,
ROUND(AVG(purchase_amount),2) as avg_purchase_amount
FROM customer
WHERE shipping_type in ('Express', 'Standard')
GROUP BY category, shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT
    CASE 
        WHEN subscription_status='Yes' THEN 'subscriber'
        ELSE 'non_subscriber'
    END as customer_type,
    COUNT(customer_id) as total_customers,
    ROUND(SUM(purchase_amount),2) as total_revenue,
    ROUND(AVG(purchase_amount),2) as avg_spend
    
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

WITH product_metrics AS (
    SELECT 
        item_purchased,
        COUNT(*) as total_orders,
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) as discount_orders,
        SUM(purchase_amount) as total_revenue,
        SUM(CASE WHEN discount_applied = 'Yes' THEN purchase_amount ELSE 0 END) as discount_revenue,
        SUM(CASE WHEN discount_applied = 'No' THEN purchase_amount ELSE 0 END) as non_discount_revenue
    FROM customer
    GROUP BY item_purchased
),
total_company_revenue AS (
    SELECT SUM(purchase_amount) as all_revenue FROM customer
)
SELECT TOP 5
    p.item_purchased,
    p.total_orders,
    p.discount_orders,
    CAST(ROUND(100.0 * p.discount_orders / p.total_orders, 2)as decimal(10,2)) as discount_order_pct,
    ROUND(p.total_revenue, 2) as total_revenue,
    ROUND(p.discount_revenue, 2) as discount_revenue,
    ROUND(p.non_discount_revenue, 2) as non_discount_revenue,
    CAST(ROUND(100.0 * p.discount_revenue / p.total_revenue, 2) as decimal(10,2)) as pct_of_product_revenue_from_discount,
    CAST(ROUND(100.0 * p.total_revenue / t.all_revenue, 2) as decimal(10,2)) as product_share_of_total_revenue,
    CAST(ROUND(100.0 * p.discount_revenue / t.all_revenue, 2) as decimal(10,2)) as discount_revenue_share_of_total
FROM product_metrics p
CROSS JOIN total_company_revenue t
ORDER BY discount_revenue_share_of_total DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
SELECT 
    customer_id, 
    previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


